name: gnssr
channels:
- anaconda
- conda-forge
dependencies:
- h5netcdf=1.7.3
- python-dotenv=1.2.1
- geopandas=1.1.1
- expat=2.7.1
- netcdf4=1.7.3
- ipykernel=6.30.1
- pip=25.2
- xarray=2025.10.1
- xz=5.8.1
- matplotlib=3.10.7
- simplekml=1.3.6
